services:
  - type: web
    name: QR-Scanner
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libjpeg-dev zlib1g-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
